apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    repoURL: 'https://github.com/solorpeng/block-buster.git'
    targetRevision: HEAD
    path: 'nginx'
    kustomize:
      namePrefix: nginx-
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
